### ISSUE TITLE
rust如何链接c++静态库？

### ISSUE THREAD

**Issue by wenzhang-dev** [MashPlant/ncmdump-rs#1]
Hi, 

我是从《在Rust的wasm后端中链接C++》文章过来的，有一个类似的问题想请教一下。

我有一个Rust库，并且提供了C接口。我用c++重新将这些C接口封装了一下。
我也想将c++代码和rust，使用wasm打包在一起。

遇到的问题是，如果使用emcc将c++代码编译成wasm，并在Rust在.cargo/config的rustflags中指定link-args，链接这个wasm。
但是编译出的wams和胶水代码，并没有处理c++中有关STL库的符号。wasm_bindgen正常，效果像这样，
![image](https://user-images.githubusercontent.com/37389563/148531708-e79610f6-cd65-493e-b7da-b76a53452382.png)

下面env中，很奇怪的符号，就是c++ mangle的符号

请问一下，有什么方法，能同时处理wasm_bindgen符号，还可以把c++的符号正常决议吗？

**Comment by MashPlant** [comment]
这些参数看起来应该是C++ stdlib的一部分，不应该需要从env来import，或许你的链接参数不对？

就是博客中的这一段：

```rust
fn main() {
  println!("cargo:rerun-if-changed=src/add_tag.cpp");
  println!("cargo:rustc-flags=-L<taglib>/build/taglib -l tag -L<emscripten>/system/local/lib -L<emscripten>/system/lib -L<emscripten>/cache/wasm -l c -l compiler_rt -l c++-noexcept -l c++abi-noexcept -l dlmalloc -l pthread_stub -l c_rt_wasm -l sockets");
  cc::Build::new().file("src/add_tag.cpp").include("/usr/include/taglib").compile("add_tag");
}
```

也有可能是emcc默认不链接C++ stdlib，换用em++试试？

**Comment by wenzhang-dev** [comment]
非常谢谢，确实是链接参数问题。
